language: java
jdk:
  - openjdk19

# Cache dependencies to speed up builds
cache:
  directories:
    - $HOME/.m2

# Install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y openjfx

# Build and test
script:
  # Build the project
  - mvn clean install --batch-mode --no-transfer-progress
  
  # Run unit tests
  - mvn test --batch-mode --no-transfer-progress
  
  # Run JavaFX tests with virtual display
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - mvn test -P ui-tests --batch-mode --no-transfer-progress

# Only build these branches
branches:
  only:
    - main

# Environment variables
env:
  global:
    - MAVEN_OPTS="-Xmx2048m"
    - TEAMCITY_SERVER=cleansweep.teamcity.com


# TeamCity integration
after_success:
  # Trigger TeamCity build
  - |
    if [ "$TRAVIS_BRANCH" = "main" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      curl -X POST \
        "https://$TEAMCITY_SERVER/app/rest/buildQueue" \
        -H "Authorization: Bearer $TEAMCITY_TOKEN" \
        -H "Content-Type: application/xml" \
        -H "Accept: application/json" \
        -d "<build><buildType id='id135e61f841174c0fB288277eacd25adb_PipelineHead'/></build>"
    fi


# Build status notifications
notifications:
  webhooks:
    urls:
      - https://$TEAMCITY_SERVER/app/rest/builds/
    on_success: always
    on_failure: always